### PR TITLE
[RGTC-1875] Replace drupal_get_path

### PR DESCRIPTION
**Pull request by shuklina**
Do not merge PR, only review it and approve/request changes.
Merge is allowed by QA Engineer only.

**Related Issue/Ticket:**

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

(Replace this line with a link to the related GitHub issue on [ymcatwincities/openy_gated_content](https://github.com/ymcatwincities/openy_gated_content/issues) or your own ticketing system)

## Steps to test:

- [ ] First do this
- [ ] Then do this (and look at this great screenshot).
- [ ] Finally observe the issue is resolved.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by podarok — DISMISSED** [review]

**Review by anpolimus — APPROVED** [review]
Code looks ok.

**Review by podarok — DISMISSED** [review]

**Review by podarok — APPROVED** [review]

**Review by podarok — APPROVED** [review]

**Comment by podarok** [comment]
@anpolimus your turn

**Review by anpolimus — APPROVED** [review]
Code looks ok

**Comment by anpolimus** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested.
1. There is a gap between the megamenu and secondary menu on Rose theme
image

**Comment by anpolimus** [comment]
@AnastasiiaPys let's log that UI bug for now and merge it since it blocked Drupal 9.3

**Comment by anpolimus** [comment]
New fixes are here: https://github.com/fivejars/openy_gated_content/pull/446

**Pull request closed without merging**
