### PR TITLE
PRODDEV-518 Logo, the Close  button and buttons should be displayed i…

### PR DESCRIPTION
**Pull request by jediandrey**
https://openy.atlassian.net/browse/PRODDEV-518

### CODE REVIEW

**Comment by jediandrey** [comment]
retest

**Comment by jediandrey** [comment]
retest this

**Comment by jediandrey** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested on Iphone 11, Samsung S10E, Ipad, Samsung Tab S6 Lite.

Issue still exist on Carnation theme
image

**Comment by AnastasiiaPys** [comment]
Retested.

All good.

**Review by anpolimus — APPROVED** [review]

**Pull request merged**
