### PR TITLE
[PRODDEV-431] Refactor listings to have the same behavior everywhere.…

### PR DESCRIPTION
**Pull request by NightHunterSV**
… Hide "More" buttons if there is no extra content except the one already shown in the listing.

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-431

## Steps to test:

- [ ] Log in to a site
- [ ] Visit the VY home page, category page, favorites page, video/blog/event/personal training detailed pages.
- [ ] Check that you can see the "More ->" links on the listings only when there is more content than the one already displayed on the listing.

Screenshot-20210908194927-1614x1730

Screenshot-20210908195013-1612x1372

- [ ] Check that you can use pagination on the events' listings: visit the "Yoga" category, click "More ->" to get to the full events' listing:

Screenshot-20210908194830-1804x1546

- [ ] Check the pagination is shown and working as earlier: after the "More ->" clicked on the home page, category or "Favorites" page, and the items count per page can be changed at the VY settings page.
- [ ] Finally observe the issue is resolved.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by hamrant — APPROVED** [review]
@NightHunterSV please add to steps for review all places that can be affected by your refactoring

**Comment by AnastasiiaPys** [comment]
Tested on macOS(Chrome, Safari),Iphone 11.
- The ' More' link is missing for videos on the Home page although there are more than 8 videos
image

**Review by anpolimus — APPROVED** [review]
Code is ok.
But we have to think about adding a new component, called View All that will have all logic inside itself.

**Comment by AnastasiiaPys** [comment]
Tested on macOS(Chrome, Safari),Iphone 11, Windows 10(Edge), Ipad

All good

**Pull request merged**
