### PR TITLE
[VYMCA-126] Fix access checks and returned categories array

### PR DESCRIPTION
**Pull request by NightHunterSV**
https://3.basecamp.com/3608022/buckets/17045978/todos/3332684892

## Steps to test:

- [ ] Log in as an admin
- [ ] Create a test user with the Virtual Y Editor role
- [ ] Ensure you're able to see the VY content

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]
Code is ok, but we have to very carefully test this build since permissions logic was changed a lot.

**Review by hamrant — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
Tested, requirements from R1.2 Exclude virtual_ymca_editor from category access check - Virtual YMCA are not done. I can see the content on the listed URL's

**Comment by froboy** [comment]
@hamrant I don't have access to Basecamp so I can't see the original requirement, but a quick scan this seems ok. It looks like it doesn't change what's required of `getVirtualyEditorRoles()`, correct? Just how that's processed.

**Comment by hamrant** [comment]
@froboy yep, there also fixed issue with access to content in app for editor role

**Comment by NadyaRudenko** [comment]
discussed in Slack, that for the listed URL's Virtual YMCA Editor SHOULD see the content. As on any other front-end pages. PR is ready for merge 🥳

**Pull request merged**
