### PR TITLE
Resolved outlook spaces issue.

### PR DESCRIPTION
**Pull request by bharath-kondeti**
**Related Issue/Ticket:**

https://github.com/ymcatwincities/openy_gated_content/issues/71

**Steps to Test:**
- Visit a VY site and login.
- Go to Live streams and select one of the live stream.
- From "Add to Calendar" dropdown, select outlook or office365. The '+' character is not appearing anymore.

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]
Code is ok. Sending to QA.

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
retest

**Comment by anpolimus** [comment]
retest

**Comment by froboy** [comment]
Calendar_-_Schwab__Avi_-_Outlook

I tested with the "Outlook 365" link and this worked! I don't have a non-work outlook account, but it seems like they should both work the same.

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
Tested on Chrome, confirming that there no + signs anymore. looks good, thanks
image

**Comment by hamrant** [comment]
@bharath-kondeti please merge fivejars:master branch to your branch and rebuild application

**Pull request merged**
