### PR TITLE
FE fixes for PRODDEV-349

### PR DESCRIPTION
**Pull request by Sardis93**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-349

## Steps to test:

- [ ]  Log in to VY as an admin
- [ ]  Enable PTs module
- [ ] Add Virtual trainer role for admin
- [ ]  Open site in another browser / anonymous mode
- [ ]  Log in as a user
- [ ]  As an admin, create PT and reference self at the Trainer field, newly created user -- as a Customer
- [ ]  From the VY dashboard, navigate to the PT you've created
- [ ]  Join the meeting
- [ ]  Verify there is a sound indicator, and its size depends on the input volume:

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]

**Comment by Sardis93** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested on macOs(Safari, Chrome), Windows 10( Edge), Ipad Air, Iphone 11
Issues with indicators are fixed. But I noticed that the volume indicator on the Iphone does not work. (Pay attention to volume indicator at the bottom)
https://user-images.githubusercontent.com/76169576/123247975-1127e980-d4f0-11eb-848d-2b328fda348a.mp4
And there is small green line on instructor's screen incase the user is connected from macOs(Safari)
image

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
retest

**Review by NightHunterSV — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested on macOs(Safari, Chrome), Windows 10( Edge), Ipad Air, Iphone 11.
Works good on  macOs(Safari, Chrome), Windows 10( Edge), Ipad Air

**Pull request merged**
