### PR TITLE
Fixed caching issue for Daxko SSO

### PR DESCRIPTION
**Pull request by anpolimus**
**Related Issue/Ticket:**

Final fixes for daxko sso caching issue.
Login form now works properly.

## Steps to test:

- [ ] Configure daxko_sso auth method
- [ ] Test immediate redirect mode. User should be redirected directly to daxko from /virtual-y-login page
- [ ] Test form mode. User should see different content for `/virtual-y-login page` and `/virtual-y-login page?error=1`

### CODE REVIEW

**Review by hamrant — APPROVED** [review]

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
retest

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
@anpolimus why we have a log in link instead of a button on Rose and Carnation?
link on carnation
link on rose

**Comment by anpolimus** [comment]
retest

**Comment by NadyaRudenko** [comment]
retested, all good. Thanks, @anpolimus 🙂

**Comment by anpolimus** [comment]
retest

**Pull request merged**
