### PR TITLE
[PRODDEV-193] Give access for Virtual Y Instructor to view any training

### PR DESCRIPTION
**Pull request by hamrant**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-193

## Steps to test:

- [ ] Login as **admin**
- [ ] Go to `/admin/modules`
- [ ] Enable `Open Y Virtual YMCA PT` module
- [ ] Login as **dummy** user in a new browser session
- [ ] As **admin** assign to dummy user "Virtual trainer" role
- [ ] As **dummy** user open "/admin/virtual-y/personal_training/add"
- [ ] Check that you have access to create training
- [ ] Create training
- [ ] Check that you can view/edit/delete training

**Note:** to have different users in autocomplete you should activate them on "/admin/people"

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by NightHunterSV — APPROVED** [review]

**Review by anpolimus — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by AnastasiiaPys — APPROVED** [review]
All good

**Comment by AnastasiiaPys** [comment]
Testing passed

**Pull request merged**
