### PR TITLE
[PRODDEV-173] IE11 svg-related fixes

### PR DESCRIPTION
**Pull request by NightHunterSV**
https://openy.atlassian.net/browse/PRODDEV-173

## Steps to test:

- [ ] Log in to an app using IE11
- [ ] Ensure all the points from the task are fixed
- [ ] Ensure the "Scroll to top" button looks fine (the arrow is inside a circle)
- [ ] Ensure the "categories" icon is visible on the Live Stream and Virtual Meeting near the categories' name(s)

### CODE REVIEW

**Comment by NightHunterSV** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by NightHunterSV** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
Code looks ok, ready for testing

**Comment by NadyaRudenko** [comment]
I see a big space between title and other content on live stream and virtual meeting pages 
image
image

**Comment by NadyaRudenko** [comment]
Retested, looks better. Thank you! 🙂

**Pull request merged**
