### PR TITLE
[VYMCA-106] Implement "Scroll to top" button

### PR DESCRIPTION
**Pull request by NightHunterSV**
Steps for review:
- [ ] Scroll down the page with an app and ensure the "Scroll to top" button appears
image

- [ ] Ensure the "Scroll to top" button works: scrolls the viewport to the VY app top

### CODE REVIEW

**Comment by hamrant** [comment]
The code looks ok, works great.

One note from my side: on the footer scroll to top button not clickable:

Screenshot from 2020-12-03 13-02-40

And a small question: do we need a white border around the scroll to top button?

cc @NightHunterSV

**Comment by NightHunterSV** [comment]
> on the footer scroll to top button not clickable:

Now it should be
 
> do we need a white border around the scroll to top button?

Yes, it's according to the designs

cc @hamrant

**Review by hamrant — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
- two arrows on Lily
image

- Lily and Rose (on desktop): can't scroll the page after clicking the top arrow

**Comment by hamrant** [comment]
retest

**Comment by NadyaRudenko** [comment]
retested, fixed. thank you!

**Pull request merged**
