### PR TITLE
Make "more" link more noticable

### PR DESCRIPTION
**Pull request by froboy**
**Related Issue/Ticket:**

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

https://github.com/ymcatwincities/openy_gated_content/issues/131

## Steps to test:

- [ ] Log in as a member
- [ ] observe more More

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Review by hamrant — APPROVED** [review]

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
code is ok.
Fixing build and sending to QA.

**Comment by anpolimus** [comment]
retest

**Comment by hamrant** [comment]
retest

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. Looks good for me.

**Pull request merged**
