### PR TITLE
Update combine method for multi-value fields

### PR DESCRIPTION
**Pull request by froboy**
Now that Category is a multi-value field, the fix from #97 no longer applies. This adds the same check to the multi-value field section in `JsonApiCombineMixin.js`

See https://github.com/ymcatwincities/openy_gated_content/issues/24 for test steps.

### CODE REVIEW

**Comment by hamrant** [comment]
retest

**Comment by hamrant** [comment]
On home page works fine, but categories page empty: http://carnation.pr-105.openy-gated-content.sandbox-2.ci.fivejars.com/virtual-ymca#/categories

Screenshot from 2020-09-15 19-35-36

Let's wait https://github.com/fivejars/openy_gated_content/pull/104 merge (here was rebuilded categories components) and return back to this issue and improve display when there no categories.

**Comment by anpolimus** [comment]
@hamrant , @froboy  Ihor is right. A lot of it was done at #104 . After that this PR could be outdated.

**Comment by froboy** [comment]
@hamrant @anpolimus I tested #104 with the steps linked above and I obtained the same results. changing the base of this PR to merge into that PR.

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
Code is ok.

**Comment by anpolimus** [comment]
Steps were tested. Issue is absent.

**Pull request merged**
