### PR TITLE
[PRODDEV-345] Hide 1px green border coming from some devices' cameras

### PR DESCRIPTION
**Pull request by NightHunterSV**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-345

## Steps to test:

- [ ] Log in to VY as an admin
- [ ] Enable PTs module
- [ ] Add Virtual trainer role for admin
- [ ] Open site in another browser / anonymous mode
- [ ] Log in as a user
- [ ] As an admin, create PT and reference self at the `Trainer` field, newly created user -- as a `Customer`
- [ ] From the VY dashboard, navigate to the PT you've created
- [ ] When connecting from the iOS devices, as an example, you shouldn't see the green border on the sides.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by hamrant** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. Works as expected.

**Comment by anpolimus** [comment]
retest

**Pull request merged**
