### PR TITLE
Openy 163 Resolved Virtual Y: With Y-USA Provider, members with same first name and last name cannot authenticate with barcode

### PR DESCRIPTION
**Pull request by kairamkondarajesh**
https://github.com/ymcatwincities/openy_gated_content/issues/163

## Steps to test:

- [ ] Take pull from openy-163 branch.
- [ ] Ensure the Y-USA provide enabled in virtual-y  gc auth settings.(admin/openy/virtual-ymca/gc-auth-settings)
- [ ] Then try login with below mentioned barcodes.( from homepage)
- [ ] Finally observe every user should login into the site.

{
"Barcode": "5252083",
"Email": "pmarebear67@hotmail.com",
"FirstName": "Mary",
"LastName": "Bennett",
}
{
"Barcode": "5577444",
"Email": "Mc58bennett@gmail.com",
"FirstName": "Mary",
"LastName": "Bennett",
}
{
"Barcode": "30044273809",
"Email": "ghill7107@yahoo.com",
"FirstName": "Mary",
"LastName": "Bennett",
}

### CODE REVIEW

**Comment by AnastasiiaPys** [comment]
Tested on macOS(Chrome).
I was not able to log in to the site with all tree barcodes
image

**Comment by froboy** [comment]
@kairamkondarajesh please see above and update the test steps as necessary.

**Comment by kairamkondarajesh** [comment]
> Tested on macOS(Chrome). I was not able to log in to the site with all tree barcodes image

Can you please provide me the tree barcodes which are failing to login?

**Review by podarok — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested on macOS(Chrome), Same situation, I have an error message that user is inactive
image

**Comment by sarah-halby** [comment]
@kairamkondarajesh this failed QA again. Please review.

**Comment by kairamkondarajesh** [comment]
> Tested on macOS(Chrome), Same situation, I have an error message that user is inactive image

Are you using barcodes or Membership id to login?
Can you please provide me the barcodes which your trying to login.

**Comment by AnastasiiaPys** [comment]
@kairamkondarajesh I used barcodes that are in the steps: 5252083, 5577444,30044273809

**Comment by kairamkondarajesh** [comment]
> @kairamkondarajesh I used barcodes that are in the steps: 5252083, 5577444,30044273809

Did you enabled the 'Y-USA Provider' at admin/openy/virtual-ymca/gc-auth-settings.
image

I have configured the 'Y-USA Provider'  at admin/openy/virtual-ymca/gc-auth-settings. Now I can able to login with above mentioned barcodes.

**Comment by AnastasiiaPys** [comment]
@kairamkondarajesh I think we have different configuration that's why these barcodes don't work for me
image

**Comment by AnastasiiaPys** [comment]
retest

**Comment by kairamkondarajesh** [comment]
> @kairamkondarajesh I think we have different configuration that's why these barcodes don't work for me image

Yes, You need proper Y-USA configurations.

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
@kairamkondarajesh after the build are ready, could you configure Y-USA provider so that I can test it with mentioned barcodes?

**Comment by sarah-halby** [comment]
@kairamkondarajesh, any response to @AnastasiiaPys comment above?

**Comment by kairamkondarajesh** [comment]
> @kairamkondarajesh, any response to @AnastasiiaPys comment above?

Please test http://pr-402.openy-gated-content.sandbox-2.ci.fivejars.com/virtual-y-login

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
retest

**Pull request merged**
