### PR TITLE
Duration bug on livestream teaser and change date library to dayjs

### PR DESCRIPTION
**Pull request by retif**
**Related Issue/Ticket:**

Live Stream and Virtual Meeting duration were displayed not precise enough using moment.humanize method(for example 45 minutes it is displayed as one hour).
While fixing this problem I am also replaced momentjs with dayjs which has almost the same API, but in 2kb package, so this PR also solves the problem of unreasonable bundle size used by moments library.

## Steps to test:

- [ ] Check dates and duration displayed on live stream, virtual meeting and video teaser
- [ ] Check dates and duration displayed on live stream, virtual meeting and video page

created based on https://github.com/fivejars/openy_gated_content/pull/275

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by hamrant — APPROVED** [review]

**Comment by retif** [comment]
retest

**Comment by retif** [comment]
retest

**Comment by hamrant** [comment]
Fix for builds in https://github.com/fivejars/openy_gated_content/pull/278

**Review by anpolimus — DISMISSED** [review]

**Comment by retif** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested, all good!

**Pull request merged**
