### PR TITLE
[VYMCA-107] Implement Schedule page

### PR DESCRIPTION
**Pull request by NightHunterSV**
https://3.basecamp.com/3608022/buckets/17045978/todos/3182711603#__recording_3279752311
https://fivejars.atlassian.net/browse/VYMCA-107

## Steps to test:

- [ ] Log in to VY
- [ ] Ensure the Schedules page is opened if click on the "Schedules" top menu item.
image
image

- [ ] Ensure the page looks nearly to the designs on the desktop, tablet and mobile
image
image

- [ ] Ensure the date switcher and days columns captions (on desktop) are fixed right under the VY top menu bar.
- [ ] Check the Schedule page look in all the OpenY themes.

### CODE REVIEW

**Comment by hamrant** [comment]
```
Object { _name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location (\"/schedule\") is not allowed", stack: "", … }
```

Error on page load - http://carnation.pr-198.openy-gated-content.sandbox-2.ci.fivejars.com/virtual-ymca#/schedule

Screenshot from 2020-12-11 16-46-34

Anyway, looks ok, works fine

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
retest

**Comment by NadyaRudenko** [comment]
@NightHunterSV can you please remove heart icon from the past events?
image
as in case of adding to favorites past live stream I can see this:
image
also, on Lily and Rose all colors are light grey, but it should be #000000 according to design. On Carnation it is not black as well, but at least it looks darker.
image 
everything else looks nice, thank you 🙂

**Review by retif — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
@NightHunterSV heart icons are gone from future events + on lily I've found lost one at the bottom of the page
image
image

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
fixed. looks good to me. thank you, @NightHunterSV! 🙂

**Pull request merged**
