### PR TITLE
[PRODDEV-277] Video Chat - fix message count display on mobile

### PR DESCRIPTION
**Pull request by hamrant**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-277

## Steps to test:

- [ ] Repeat steps from https://github.com/fivejars/openy_gated_content/pull/321
- [ ] Check that message count looks ok on mobile and desctop

Screenshot from 2021-04-26 13-29-03
Screenshot from 2021-04-26 13-29-16
Screenshot from 2021-04-26 13-29-36

### CODE REVIEW

**Comment by hamrant** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
code looks good.
@AnastasiiaPys please, test on mobile.

**Comment by AnastasiiaPys** [comment]
retest

**Review by AnastasiiaPys — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested on all three Themes. Work as expected.

**Pull request merged**
