### PR TITLE
[PRODDEV-411] Install and update definitions for the fields needing t…

### PR DESCRIPTION
**Pull request by NightHunterSV**
…his.

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-411
## Steps to test:

- [ ] Go to /status
- [ ] Verify there is no messages regarding the field definitions needing updates / installation / uninstallation.
- [ ] Finally observe the issue is resolved.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
@NightHunterSV, please add to steps items with checking these fields in content types (we should double-check that all works as before fix)

**Review by anpolimus — APPROVED** [review]
Code is ok.

**Comment by anpolimus** [comment]
@NightHunterSV code is ok, but we are getting next warnings now:
Notice: Undefined index: advanced_help_block in openy_gc_shared_content_entity_bundle_field_info() (line 92 of /var/www/openy_gated_content/modules/openy_gc_shared_content/openy_gc_shared_content.module).

**Comment by anpolimus** [comment]
Virtual Y permissions field has gone at node creation page

**Comment by anpolimus** [comment]
https://www.loom.com/i/706779ef40e04bb8a7fa59d0857e472e

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
Problems were fixed. Ready for QA.

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested on macOs(Chrome).
there is no messages regarding the field definitions needing updates / installation / uninstallation.

**Pull request merged**
