### PR TITLE
replaced a plain text "Loading" by spinner component on category page

### PR DESCRIPTION
**Pull request by aleevas**
**Related Issue/Ticket:**

https://github.com/ymcatwincities/openy_gated_content/issues/79

## Steps to test:

- [ ] Log to gated content
- [ ] Go to the category video page
- [ ] You should see an animated spinner instead a plain text (if you can't see loader, you can try to enable the throttling option in your browser devTools).
Loader

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA team in Slack

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]

**Review by hamrant — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
retest

**Comment by NadyaRudenko** [comment]
tested, I don't see spinner on video categories page. it is present on the home page

**Comment by NadyaRudenko** [comment]
https://monosnap.com/file/cr9M4ys6k528ncCEfbjP1EQLBvmbsF

**Comment by aleevas** [comment]
> https://monosnap.com/file/cr9M4ys6k528ncCEfbjP1EQLBvmbsF
@NadyaRudenko it's should be fixed in this [PR](https://github.com/fivejars/openy_gated_content/pull/195)

**Comment by aleevas** [comment]
I've merge changes from this PR to another one https://github.com/fivejars/openy_gated_content/pull/195
I think we can close this PR

**Pull request closed without merging**
