### PR TITLE
[VYMCA-99] Implement export logs functionality

### PR DESCRIPTION
**Pull request by NightHunterSV**
Steps for review:
- [ ] Enable logging on the /admin/modules page:
image

- [ ] Navigate through the Virtual Y or log in to it to get some records on /admin/virtual-y-logs page
- [ ] Ensure you're able to see the "Export log records" button above the logs table and in the "Virtual Y" -> "Logs" menu
image
image

- [ ] Ensure the page is opened on click at any place specified above
image

- [ ] Ensure it's not possible to send an empty or wrong value in any field:
image
image
image

- [ ] Ensure it's possible to export data when selected the right values, and you're redirected to the `Files` page with needed filters pre-selected:
image

- [ ] Download the file and ensure it has correct data

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
Code is ok

**Comment by anpolimus** [comment]
@NightHunterSV I'm getting fatal error during my attempt to export logs
The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\csv_serialization\Encoder\CsvEncoder::setOutputHeader() in Drupal\openy_gc_log\LogArchiver->writeLogsToFiles() (line 314 of /var/www/openy_gated_content/modules/openy_gc_log/src/LogArchiver.php).
Drupal\openy_gc_log\LogArchiver->writeLogsToFiles() (Line: 167)
Drupal\openy_gc_log\LogArchiver->archive(Object, Object, ) (Line: 159)
Drupal\openy_gc_log\Form\ManualExportForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('openy_gc_log_manual_export', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Review by anpolimus — CHANGES_REQUESTED** [review]
Please, fix fatal

**Review by hamrant — DISMISSED** [review]

**Comment by hamrant** [comment]
Looks ok for me, one question, I can't download files on http://carnation.pr-149.openy-gated-content.sandbox-2.ci.fivejars.com/admin/content/files?filename=virtual-y&filemime=application/x-gzip

Got `403 Access Denied - You are not authorized to access this page.`

**Review by podarok — DISMISSED** [review]

**Comment by froboy** [comment]
@hamrant that 403 sounds like the exact issue I ran into locally. I have not yet been able to resolve it.

**Comment by froboy** [comment]
@NightHunterSV is it possible to leverage a new permission so that the access that might be configurable by site administrators instead of hard-coding the roles? Sites may use roles in different ways and some may not want editors to have the privilege or may want to give access to another custom role.

**Review by hamrant — DISMISSED** [review]

**Review by hamrant — DISMISSED** [review]
The issue with file download fixed.

cc @froboy @anpolimus

**Comment by hamrant** [comment]
Error from logs:
```
Deprecated function: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in openy_gc_log_file_download() (line 68 of /var/www/openy_gated_content/modules/openy_gc_log/openy_gc_log.module).

openy_gc_log_file_download('private://vy_logs/2020/virtual-y-logs-2020_10_18-2020_10_31_23_59_59.csv.gz')
```

One note from me (can be fixed in separate PR).

```csv
created,event_type,entity_type,entity_bundle,entity_id
1603721159,userLoggedIn,,,
1603721163,entityView,node,gc_video,3
1603721164,entityView,node,gc_video,2
1603721170,entityView,node,gc_video,4
1603721175,entityView,series,virtual_meeting,1
```

`userLoggedIn` event for dummy user doesn't contain any info, we can add there at least user id.

**Review by hamrant — APPROVED** [review]

**Pull request merged**
