### PR TITLE
[VYMCA-105] Build an app to be able to work in the IE11

### PR DESCRIPTION
**Pull request by NightHunterSV**
Based on https://github.com/fivejars/openy_gated_content/pull/165

Yet TO DO:

- on CSS build add `-ms-` prefix for grids
- on CSS build add backup values for cases when used HTML variables (especially for `vue-lazy-youtube-video` package and it's "youtube button" styling)
- think how to list the packages (ones that are in ECMAScript 2015 format) needed to be transpiled -- to not overweight the result js file.

Packages can be useful:
https://www.npmjs.com/package/vite-plugin-legacy
https://www.npmjs.com/package/postcss-ms-grid
https://www.npmjs.com/package/stylis-plugin-css-variables

### CODE REVIEW

**Comment by hamrant** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by hamrant — DISMISSED** [review]
The code looks good, let's test

**Review by hamrant — DISMISSED** [review]

**Review by hamrant — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
Testing passed.

**Pull request merged**
