### PR TITLE
Exclude virtual_ymca_editor from category access check

### PR DESCRIPTION
**Pull request by froboy**
**Related Issue/Ticket:**

https://github.com/ymcatwincities/openy_gated_content/issues/77

## Steps to test:

- [ ] log in to https://sandbox-carnation-std-virtual-y.openy.org/ and create a user with the "Virtual YMCA Editor" role
- [ ] observe that as Administrator and Member, you can see these pages:
  - [ ] /virtual-ymca#/categories/blog
  - [ ] /virtual-ymca#/categories/video
- [ ] log in as the Editor
- [ ] Observe the above pages are empty, with no error or message.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA team in Slack

### CODE REVIEW

**Comment by froboy** [comment]
I tested on the carnation build ⬆️ and the issue seems to be resolved.

**Comment by anpolimus** [comment]
@froboy code is great, but we now have a lot of places where editors role is hard-coded.
Example: https://github.com/fivejars/openy_gated_content/blob/master/src/SegmentContentAccessCheck.php#L23
Probably we have to add general trait.

**Comment by froboy** [comment]
@anpolimus yea... I based this fix off of that existing code, but I agree that we should get out of hard-coding the role. I opened https://github.com/ymcatwincities/openy_gated_content/issues/78 for further discussion of that, as i think it'll be a larger change.

**Comment by froboy** [comment]
Closing this in favor of #188

**Pull request closed without merging**
