### PR TITLE
[PRODDEV-484] Add patch to resolve indexing error

### PR DESCRIPTION
**Pull request by froboy**
Via https://www.drupal.org/project/drupal/issues/3138528

Do not merge PR, only review it and approve/request changes.
Merge is allowed by QA Engineer only.

**Related Issue/Ticket:** 

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

https://openy.atlassian.net/browse/PRODDEV-484

## Steps to test:

- [ ] Pull in this branch
- [ ] `composer update --lock` to apply the patch
- [ ] Visit `/admin/modules` and enable `Open Y Virtual YMCA Search`
- [ ] Visit `/admin/config/search/search-api/index/search_content` and index content
- [ ] Observe content is indexed without error.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by anpolimus** [comment]
Ready for @AnastasiiaPys

**Review by anpolimus — DISMISSED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. 
Data was successfully indexed but search doesn't return result
image

**There is an error on builds**
Drupal\blazy\Plugin\Field\FieldFormatter\BlazyFileFormatterBase::getEntitiesToView(Drupal\Core\Field\EntityReferenceFieldItemListInterface $items, $langcode) should be compatible with Drupal\Core\Field\Plugin\Field\FieldFormatter\EntityReferenceFormatterBase::getEntitiesToView(Drupal\Core\Field\FieldItemListInterface $items, $langcode) in include() (line 27 of modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyFileFormatterBase.php).

include('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyFileFormatterBase.php') (Line: 444)
Composer\Autoload\includeFile('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyFileFormatterBase.php') (Line: 322)
Composer\Autoload\ClassLoader->loadClass('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyFileFormatterBase')
spl_autoload_call('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyFileFormatterBase') (Line: 14)
include('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyFormatterBlazy.php') (Line: 444)
Composer\Autoload\includeFile('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyFormatterBlazy.php') (Line: 322)
Composer\Autoload\ClassLoader->loadClass('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyFormatterBlazy')
spl_autoload_call('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyFormatterBlazy') (Line: 14)
include('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyImageFormatter.php') (Line: 444)
Composer\Autoload\includeFile('/var/www/docroot/modules/contrib/blazy/src/Plugin/Field/FieldFormatter/BlazyImageFormatter.php') (Line: 322)
Composer\Autoload\ClassLoader->loadClass('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyImageFormatter')
spl_autoload_call('Drupal\blazy\Plugin\Field\FieldFormatter\BlazyImageFormatter') (Line: 113)
Drupal\Core\Field\FormatterPluginManager->getInstance(Array) (Line: 205)
Drupal\Core\Entity\Entity\EntityViewDisplay->getRenderer('field_media_image') (Line: 236)
Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) (Line: 340)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'prgf_banner') (Line: 282)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 239)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 786)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 377)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 83)
__TwigTemplate_2381ff2a59801d39ce42dd2b2d6870731a3c2bcba452460e9d091eda15f2d541->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('profiles/contrib/openy/themes/openy_themes/openy_rose/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 56)
__TwigTemplate_ca0cc426c60d086dd1438b4261d7434419e653bd2f48f349e7371bb30076d6de->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('profiles/contrib/openy/themes/openy_themes/openy_rose/templates/paragraph/paragraph--banner.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('paragraph', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 450)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 61)
__TwigTemplate_2381ff2a59801d39ce42dd2b2d6870731a3c2bcba452460e9d091eda15f2d541->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('profiles/contrib/openy/themes/openy_themes/openy_rose/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 550)
Drupal\Core\Template\TwigExtension->renderVar(Array) (Line: 66)
__TwigTemplate_25d26f0d3e15702630cb5c1c17da8074b3ad47a03806aebd63396a05f947df07->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 65)
twig_render_template('profiles/contrib/openy/themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 578)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 242)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 132)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 52)
Drupal\openy_block_date\StackMiddleware\BlockDateCacheInvalidator->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 717)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by froboy** [comment]
@AnastasiiaPys I just checked the existing build and it looks like the "Search content" index was not indexed. I reindexed it and... after all of the errors, there are results showing. I'm looking into the errors now.
Search_API___Drush_Site-Install
Cursor_and_Search_content___Drush_Site-Install

**Comment by froboy** [comment]
I've pushed a new change and retested. Two new messages that seem unrelated:

```
Notice: Undefined variable: amenities_values in openy_ckeditor_tokens() (line 70 of profiles/contrib/openy/modules/custom/openy_ckeditor/openy_ckeditor.module).
Warning: Invalid argument supplied for foreach() in _openy_ckeditor_prepare_amenities_view() (line 91 of /var/www/docroot/profiles/contrib/openy/modules/custom/openy_ckeditor/openy_ckeditor.module)
```

I'm not sure if those were appearing before or not since the other sandboxes can't index. I'm working on debugging those.

**Comment by anpolimus** [comment]
@froboy , please disregard that notice. That comes from amenities block of Open Y

**Comment by anpolimus** [comment]
@AnastasiiaPys could you please check again?

**Review by anpolimus — APPROVED** [review]

**Comment by froboy** [comment]
Thanks @anpolimus. I've opened a new issue with those to be worked on separately. https://github.com/ymcatwincities/openy/issues/2601

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. Works as expected.
Only one question. The search result should not be displayed for the anonymous user but it does. Should we fix it here or should we merge the pr, retest this functionality on demo and if the issue exist, create separate ticket in jira? @froboy @anpolimus 
image

**Comment by froboy** [comment]
@AnastasiiaPys I believe this is the expected behavior. If you compare the results from "senior" for instance as anonymous vs authenticated you can see that the "gated" content only shows for the authenticated user. What's showing for anonymous users is Locations and News items that are not gated and should be visible to everyone.

**Pull request merged**
