### PR TITLE
Category filter modal (or "pop-up") overflows page

### PR DESCRIPTION
**Pull request by froboy**
**Related Issue/Ticket:**

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

Resolves https://github.com/ymcatwincities/openy_gated_content/issues/117

## Steps to test:

- [ ] visit /virtual-ymca#/videos
- [ ] Click "Filter"
- [ ] Observe the pop-up scrolls if the window height doesn't fit all of the options.

vy_modal_fix

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [x] Tested against Carnation
  - [x] Tested against Lily
  - [x] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by froboy** [comment]
retest

**Review by hamrant — APPROVED** [review]
Code looks ok, ready for testing

**Comment by AnastasiiaPys** [comment]
Tested. Works as expected.

**Review by AnastasiiaPys — APPROVED** [review]

**Comment by froboy** [comment]
retest

**Comment by hamrant** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
retest

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
There is a lot of free space at the bottom of the popup on Ipad
https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fymcaokn-dev.oneeach.net%2Flocations%3Ftype%3Dhealth-fitness%2Cchild-care%2Cother-services%2Ch2o%26amenities&speed=1

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Retested. Issue is fixed, thanks)
image

**Pull request merged**
