### PR TITLE
[VYMCA-102] Add the entity title, instructor name and entity create d…

### PR DESCRIPTION
**Pull request by NightHunterSV**
…ate to log, allow an export data altering

https://3.basecamp.com/3608022/buckets/17045978/todos/3176044748
https://fivejars.atlassian.net/browse/VYMCA-102

## Steps to test:

- [ ] Log in as an admin and enable the "Open Y Virtual YMCA Log" module
- [ ] Log in to the VY and navigate through the app
- [ ] Choose "Virtual Y" -> "Logs" -> "Export log records" in the menu
- [ ] Select dates you wanna export records for.
- [ ] Ensure there are all the needed data in the exported file.
Screenshot from 2020-12-07 12-18-15

- [ ] Choose "Virtual Y" -> "Logs" in the menu
- [ ] Ensure there are links on the "Entity Info" column -- to check the viewed or played entities' info.
image (3)

## Quality checks:

- [x] No updates are necessary for this change.
- [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA team in Slack

### CODE REVIEW

**Comment by NightHunterSV** [comment]
restart

**Comment by hamrant** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
Screenshot from 2020-12-04 20-15-47

@NightHunterSV news columns names missed

**Review by hamrant — APPROVED** [review]

**Comment by hamrant** [comment]
Looks ok, @NadyaRudenko you can test this PR.

**Comment by NadyaRudenko** [comment]
looks good to me. thanks!

**Pull request merged**
