### PR TITLE
[VYMCA-113] Update demo content for VY.

### PR DESCRIPTION
**Pull request by NightHunterSV**
https://3.basecamp.com/3608022/buckets/17045978/todos/3292272974
https://fivejars.atlassian.net/browse/VYMCA-113

## Steps to test:

- [ ] Log in to VY
- [ ] Ensure that all the videos are available on the build.
- [ ] Ensure all the videos' categories, trainers, etc. are correctly set.
- [ ] Ensure all existing content left unchanged.

### CODE REVIEW

**Review by hamrant — APPROVED** [review]
Code looks ok

**Comment by hamrant** [comment]
1) Strange Equipment data

http://carnation.pr-205.openy-gated-content.sandbox-2.ci.fivejars.com/virtual-ymca#/video/230ce824-210e-463f-9375-3b474ac1bd71 

Screenshot from 2020-12-16 17-18-14

2) Why for bootcamp not used thumbnails from youtube ?
Screenshot from 2020-12-16 17-18-58

3) Please add 2 more videos as featured on home page

4) For some reason "Up next" loading too long (not related to current PR, let's create separated issue for this)

**Review by anpolimus — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
1. Some content titles are different in build than in Basecamp. 
Time is missing in the titles.

- Content Title is 'Strength Training Exercise Workout with Jennifer at the Y!' but should be  '25-Minute Strength Training Exercise Workout with Jennifer at the Y!'.
- Content Title is Senior Fitness Workout from Home! but should be 'Senior Fitness 20-Minute Workout from Home!'
- Content Title is 'Bodyweight Bootcamp with Jen - Four by Five, it’s Good to be Alive!' but should be Bodyweight 'Bootcamp with Jen - Four by Five, it’s Good to be Alive! (30 Minute Workout No Equipment)'
-Content Title is  'Strength Turkey Burner with Sarah at the Y!' but should be 'Strength Turkey Burner with Sarah at the Y! (25 minutes)'.
 - Content Title is 'Bodyweight Bootcamp Workout to Burn off the Holiday Weight!' but should be 'Bodyweight Bootcamp Workout after (Just 20 Minutes to Burn off the Holiday Weight!)'.
 - Content Title is 'Barre Fusion Class with Jennifer!' but should be '20-Minute Barre Fusion Class with Jennifer!'
 - Content Title is 'Senior Fitness! A ForeverWell Combo Workout with Jennifer!' but should be 'Senior Fitness! A 25-Minute ForeverWell Combo Workout with Jennifer!'
 - Content Title is 'Cardio Workout with Jennifer' but should be '20-Minute Cardio Workout with Jennifer'.
 - Content Title is 'Yoga with Jen - "Creating Space for What You Need!' but should be '235-Minute Yoga with Jen - "Creating Space for What You Need!'.

 2. Content with title 'Strength Turkey Burner with Sarah at the Y!' has wrong Category.
   Category: Bootcamp but it should be Category: Strength, ForeverWell.
   
 3. Some equipment is missing in content with title 'Yoga with Jen - "Creating Space for What You Need'
 Need to add to equipment - Straw

**Comment by NightHunterSV** [comment]
> 1. Some content titles are different in build than in Basecamp.
>    Time is missing in the titles.

This was removed on purpose -- to reduce titles' length, as very long ones are looking bad on the frontend, while the needed info, especially video length, will be available even on the video preview in a new design.

> 1. Content with the title 'Strength Turkey Burner with Sarah at the Y!' has the wrong Category.
>    Category: Bootcamp but it should be Category: Strength, ForeverWell.

Should be fixed now. Please, check

> 2. Some equipment is missing in content with the title 'Yoga with Jen - "Creating Space for What You Need'
>    Need to add to equipment - Straw

I assume you're about "THE BEST Blueberry Banana Smoothie for a Healthy Day" video? Should be fixed now. Please, check.

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Testing passed.

**Pull request merged**
