### PR TITLE
Resolve "Warning: illegal offset '_original_delta'"

### PR DESCRIPTION
**Pull request by Sardis93**
**Related Issue/Ticket:**
When saving/updating any node or entity, that has `field_vy_permission`, php warning is displayed with the message:
```
Warning: Illegal string offset '_original_delta' in Drupal\Core\Field\WidgetBase->extractFormValues() (line 381 of core/lib/Drupal/Core/Field/WidgetBase.php).
```

## Steps to test:
- [ ] Enable `openy_gated_content` module
- [ ] Create or update any node of any type

## Quality checks:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by anpolimus** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
@AnastasiiaPys please test it. Code is ok.

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. I have this issue after saving the blog post
image
@anpolimus

**Comment by hamrant** [comment]
retest

**Comment by Sardis93** [comment]
retest

**Pull request closed without merging**
