### PR TITLE
[PRODDEV-285] Add images back into VY as optional field

### PR DESCRIPTION
**Pull request by NightHunterSV**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-285

## Steps to test:

- [ ] Log in to a site as an admin
- [ ] Verify there is a setting a setting `Show cover image on teaser` for each component in the VY settings
- [ ] Verify the images are shown or hidden, depending on this setting
- [ ] Verify the width (on a desktop) of the teasers is adaptive in the listings -- when cover images are disabled
- [ ] Verify the width is 25% on the desktop -- when the cover images are enabled

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by podarok — APPROVED** [review]

**Review by hamrant — CHANGES_REQUESTED** [review]
The code looks good.
@NightHunterSV one minor thing, please make image field in the events not required

**Comment by NightHunterSV** [comment]
> The code looks good.
> @NightHunterSV one minor thing, please make image field in the events not required

Done
Check, please

**Review by hamrant — DISMISSED** [review]

**Review by anpolimus — DISMISSED** [review]
Code is ok

**Comment by anpolimus** [comment]
@AnastasiiaPys , please test.

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested. Looks good for me)

**Pull request merged**
