### PR TITLE
[PRODDEV-423] Update dependencies and patches.

### PR DESCRIPTION
**Pull request by NightHunterSV**
**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-423

## Steps to test:

- [ ] Add / edit some Event series / instances
- [ ] Verify everything goes as expected.
- [ ] Verify the event instances' titles are present on their series' deletion screen:

Screenshot-20210830180713-1216x1372

- [ ] Finally observe the issue is resolved.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by anpolimus — APPROVED** [review]
Code is ok.

**Comment by anpolimus** [comment]
Ready for QA

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested on macOs(Chrome).

Works as expected. Only one question.
 Should not I test the case when the user account that is used as author for an event series is deleted? ( issue description in Jira)
 
 @anpolimus @hamrant @NightHunterSV

**Comment by NightHunterSV** [comment]
> Should not I test the case when the user account that is used as author for an event series is deleted? ( issue description in Jira)

@AnastasiiaPys , sure, this point should be also checked, as it is in the JIRA task related :)

**Pull request merged**
