### PR TITLE
Enable pagination for video listing on category page when video filter is selected

### PR DESCRIPTION
**Pull request by retif**
GitHub Issue: https://github.com/ymcatwincities/openy_gated_content/issues/115
Jira Ticket: https://openy.atlassian.net/browse/PRODDEV-238

## Steps to test:

- [ ] Create 10 videos
- [ ] Open Category page
- [ ] Click "More" button on video listing
- [ ] Use pager to see all items

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Review by hamrant — CHANGES_REQUESTED** [review]
The code looks ok, but I think we need the same fix for the rest of the components on the category page:

- EventListing (live_stream)
- EventListing (virtual_meeting)
- BlogListing

**Review by hamrant — APPROVED** [review]
The code looks good for me

**Comment by froboy** [comment]
@hamrant @retif is it not possible to have the pager appear on the category page before you have to click "more"? Going to the category page and then having to click more seems repetitive.

**Comment by froboy** [comment]
I did, however, test and the fix does work as described.

**Comment by hamrant** [comment]
@froboy we displayed several content types on the category page and can't show pager for all of them at one time... So it disabled by default and displayed when we select one content type in filters or press "more"

**Comment by froboy** [comment]
@hamrant got it. Thanks!

**Comment by retif** [comment]
it seems possible in theory, if we change query param ?page to something like ?page[content-type] but It will require changing a bunch of components to make it work, what do you think @hamrant ?

**Comment by hamrant** [comment]
@retif we can do this, but I'm not sure it's a good idea from a UI perspective.

cc @froboy

**Pull request merged**
