### PR TITLE
Enabled scheduler for blogpost and vyvideo content types.

### PR DESCRIPTION
**Pull request by kairamkondarajesh**
**Related Issue/Ticket:**

https://github.com/ymcatwincities/openy_gated_content/issues/99
JIRA: https://openy.atlassian.net/browse/PRODDEV-198

Steps to test:

Navigate to admin/structure/types
Edit the content type(Virtual Y blog post, Virtual Y Video)
For Virtual Y blog post - admin/structure/types/manage/vy_blog_post
For Virtual Y Video - admin/structure/types/manage/gc_video
Observe the Scheduler vertical tab and check if its enabled.
Expected results: Scheduler should be enabled for Virtual Y blog post, Virtual Y Video content types.

### CODE REVIEW

**Comment by froboy** [comment]
VIRTUAL_Y_Login___Open_Y_Sandbox_-_carnation
I'm seeing some strange behavior in http://upgrade.pr-256.openy-gated-content.sandbox-2.ci.fivejars.com/ but it seems totally unrelated to the PR so hoping it's just something with that db. 

I've confirmed the scheduler is enabled for VY Videos and Blog posts and config matches that of Landing Pages. 

@anpolimus this is ready for the OY team to review.

**Review by hamrant — CHANGES_REQUESTED** [review]
Let's add a dependency to the `scheduler` module in `openy_gc_storage.info.yml`

**Comment by kairamkondarajesh** [comment]
> Let's add a dependency to the `scheduler` module in `openy_gc_storage.info.yml`

I just noticed that 'drupal:scheduler' is already mentioned under the dependencies in 'openy_gc_storage.info.yml'.

**Comment by froboy** [comment]
https://github.com/fivejars/openy_gated_content/pull/256/files#diff-2c77ddca77a4bdfff7edca8983bcf3dd1f6c7fcf5efa60869afc9fc6b6105037R3-R6

Indeed it is. Strange it was there but not on. Thanks for confirming!

**Review by anpolimus — APPROVED** [review]

**Comment by anpolimus** [comment]
Ready for QA.

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested, scheduler is enabled for Virtual Y blog post, Virtual Y Video content types. All good)

**Pull request merged**
