### PR TITLE
Updated recurring events views.

### PR DESCRIPTION
**Pull request by anpolimus**
**Related Issue/Ticket:**
https://openy.atlassian.net/browse/PRODDEV-182

## Steps to test:

- [ ] Go to /admin/content/events/instances
- [ ] Check that Title Event Date Created Changed are sortable
- [ ] Check the same logic at update instance.
- [ ] Go to /admin/content/events/series
- [ ] Check that Title Created Changed are sortable

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by hamrant — APPROVED** [review]
Code looks ok

**Comment by AnastasiiaPys** [comment]
Tested. Works as expected on these pages /admin/virtual-y/events/instances , /admin/virtual-y/events/series

**Pull request merged**
