### PR TITLE
[VYMCA-116] Provide search functionality

### PR DESCRIPTION
**Pull request by NightHunterSV**
https://fivejars.atlassian.net/browse/VYMCA-116

## Steps to test:

- [ ] Log in as an admin
- [ ] (openy_carnation) Enable the search icon display in the theme settings (/admin/appearance/settings/openy_carnation)
image

- [ ] Enable the `Open Y Virtual YMCA Search` module and all the modules it depends on.
image

- [ ] Go to the Search API settings page, `Search content` index, and run the indexation using `Index now` button
image

- [ ] Ensure the content was indexed successfully
image

- [ ] Ensure you're logged in as a user with `administrator` or one of the Virtual Y roles.
- [ ] Return to the site homepage and try to search for some content:
image

- [ ] Ensure the link leads you to the content in a Virtual Y if the page found is related to an app content -- or to the page directly for other content

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by anpolimus** [comment]
Lets postpone it to 1.2 since we will have everything connected with search there.

**Comment by anpolimus** [comment]
Code is ok.

**Review by hamrant — APPROVED** [review]

**Comment by anpolimus** [comment]
retest

**Comment by anpolimus** [comment]
We are good to start testing.

**Comment by hamrant** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by AnastasiiaPys** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested.Testing passed.

**Pull request merged**
