### PR TITLE
PRODDEV-395, PRODDEV-394 Assign form-control css class to text input …

### PR DESCRIPTION
**Pull request by Sardis93**
**Related Issue/Ticket:**

[PRODDEV-394](https://openy.atlassian.net/browse/PRODDEV-394)
[PRODDEV-395](https://openy.atlassian.net/browse/PRODDEV-395)

## Steps to test:

As admin:
- [ ] log in
- [ ] install 1on1 meeting module
- [ ] create 1on1 meeting
- [ ] open meeting and click on join button

As user:
- [ ] log in
- [ ] open created meeting
- [ ] click join button

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

### CODE REVIEW

**Comment by Sardis93** [comment]
retest

**Comment by AnastasiiaPys** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by hamrant** [comment]
retest

**Review by hamrant — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
Tested on macOs(Chrome, Safari), Windows 10( Edge), Ipad, Iphone 11

Looks good to me.

**Pull request merged**
