### PR TITLE
[VYMCA-102] Change the player and add video events logging

### PR DESCRIPTION
**Pull request by NightHunterSV**
Change the player and add video playback start, pause, ended logging.

Steps for review:
- [ ] Log in as an admin
- [ ] Enable `Virtual Y Log` module
- [ ] Log in as a virtual_y role user
- [ ] Ensure the Youtube and Vimeo videos are both renderable and are looking the same as earlier, without regressions
- [ ] Add or change an existing Live stream. You can use some Vimeo event from the https://vimeo.com/search?live=now&price=free page. (Use `https://vimeo.com/event/{VIDEO_ID}/embed` format when creating or changing the media for a stream). Ensure the event video will be displayed fine in the player (the right proportions, etc.)
- [ ] Navigate through the VY, start, pause, and wait till the video finish for some videos and streams.
- [ ] Go to the `Virtual Y` -> `Logs` (/admin/virtual-y-logs)
- [ ] Ensure there are logs of your actions about the video playback operations

### CODE REVIEW

**Review by hamrant — APPROVED** [review]
Code looks on, need regression testing for video player

**Comment by hamrant** [comment]
Can we add some delay to minimize logs? For example when I press stop-play, in logs data duplicated, for 1 click - two records.

Screenshot from 2020-11-16 16-08-48

All new events for logs tested - works fine

**Review by podarok — APPROVED** [review]

**Review by hamrant — DISMISSED** [review]

**Comment by hamrant** [comment]
Tested, works great:
Screenshot from 2020-11-18 16-46-26

**Comment by NadyaRudenko** [comment]
Tested, Vimeo failed

If Vimeo stream is live at the moment when you view 'live stream', it starts to play by itself, meaning that you don't click the 'play' button. Which means we have 'videoPlaybackStarted' log, but the user does not intend to play it

**Comment by NightHunterSV** [comment]
@NadyaRudenko , please, recheck now

**Review by anpolimus — APPROVED** [review]

**Comment by NadyaRudenko** [comment]
Retested, fixed. Thank you 🙂

**Pull request merged**
