### PR TITLE
Add 'status' field to 'shared_content_source' entity type.

### PR DESCRIPTION
**Pull request by jediandrey**

### CODE REVIEW

**Comment by jediandrey** [comment]
retest

**Comment by anpolimus** [comment]
retest

**Comment by hamrant** [comment]
retest

**Comment by hamrant** [comment]
retest

**Review by hamrant — DISMISSED** [review]

**Comment by anpolimus** [comment]
@jediandrey it is not completed.
https://3.basecamp.com/3608022/buckets/17045978/todos/2963668100
> At the client, after save Server action, we have to show a message:
Your request to use Virtual Y Shared Content network was sent. You can use it after administrator's approval

**Review by anpolimus — CHANGES_REQUESTED** [review]
Please see my comment

**Review by anpolimus — APPROVED** [review]

**Review by hamrant — APPROVED** [review]

**Pull request merged**
