### PR TITLE
Added youtube player attributes handler

### PR DESCRIPTION
**Pull request by kairamkondarajesh**
https://github.com/ymcatwincities/openy_gated_content/issues/104

If a video is from YouTube, we need to check the related videos from the same author.

### CODE REVIEW

**Comment by froboy** [comment]
@kairamkondarajesh when you update JS you need to commit a built version as well. Please run `npm install` then `npm run build` from `js/gated_content`.

**Comment by anpolimus** [comment]
@kairamkondarajesh thanks for your PR. It is great that player-vars were fixed in the npm package that we are serving.
Please fix build and we are ready to move forward.

**Comment by anpolimus** [comment]
@kairamkondarajesh please remember that all changes instead of hotfixes should go to the release branches.
The current release branch is: 1.3
I've switched the base of this PR for you.
cc @froboy

**Comment by froboy** [comment]
@anpolimus is it normal that this PR is showing other changes even though the target branch has been merged in?

**Comment by anpolimus** [comment]
@kairamkondarajesh may I ask you to rebuild app again?

**Comment by kairamkondarajesh** [comment]
> @kairamkondarajesh may I ask you to rebuild app again?

@anpolimus I have run rebuild and committed the code. Please review.

**Comment by anpolimus** [comment]
retest

**Review by anpolimus — APPROVED** [review]

**Comment by AnastasiiaPys** [comment]
retest

**Comment by hamrant** [comment]
retest

**Comment by AnastasiiaPys** [comment]
Tested. testing passed.

**Comment by AnastasiiaPys** [comment]
Tested. Testing passed.

**Pull request merged**
